name = "pre-draft-mailer"
type = "javascript"
zone_id = ""
account_id = "82321a9ff91bb528e4b1d1541178417f"
route = ""
workers_dev = true
compatibility_date = "2022-02-22"
kv_namespaces = [ 
         { binding = "MAIN_NAMESPACE", id = "09c8b3bed203411e802783a907d54c32" }
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

[vars]
ZOHO_API_MAIL = "https://mail.zoho.com/api/accounts/6077046000000008002/messages"
ZOHO_API_AUTH = "https://accounts.zoho.com/oauth/v2/token"
SUBGRAPH_API = "https://api.thegraph.com/subgraphs/name/telediskodao/resolution"
EMAIL_FROM = "test@teledisko.com"
EMAIL_TO = "miotto@posteo.de"
EMAIL_CC = "alberto@granzotto.net,stefano.ceschib@gmail.com"
ODOO_API = "https://odoo.teledisko.com/jsonrpc"

[secrets]
# ZOHO_CLIENT_ID
# ZOHO_CLIENT_SECRET
# ZOHO_REFRESH_TOKEN

[miniflare]
env_path = ".env.test"             # --env
kv_persist = false                  # --kv-persist
cache_persist = "./cache"          # --cache-persist