type = "javascript"
zone_id = ""
account_id = "82321a9ff91bb528e4b1d1541178417f"
route = ""
compatibility_date = "2022-02-22"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

[env.staging]
workers_dev = true
name = "teledisko-mailer-staging"
kv_namespaces = [ 
         { binding = "MAIN_NAMESPACE", id = "89a5769623b94eb89c5e125ca58f48a0" }
]
[env.staging.vars]
ZOHO_API_MAIL = "https://mail.zoho.com/api/accounts/6077046000000008002/messages"
ZOHO_API_AUTH = "https://accounts.zoho.com/oauth/v2/token"
SUBGRAPH_API = "https://graph.dao-staging.teledisko.com/subgraphs/name/TelediskoDAO/dao"
EMAIL_FROM = "dao@teledisko.com"
EMAIL_TO = "miotto@posteo.de"
EMAIL_CC = "alberto@granzotto.net,stefano.ceschib@gmail.com"
ODOO_API = "https://odoo.teledisko.com/jsonrpc"
DAO_URL = "https://dao-staging.teledisko.com"

[env.production]
name = "teledisko-mailer"
workers_dev = false
kv_namespaces = [ 
         { binding = "MAIN_NAMESPACE", id = "a0b708c029014b33a11de9cd1cc1dbf6" }
]
[env.production.vars]
ZOHO_API_MAIL = "https://mail.zoho.com/api/accounts/6077046000000008002/messages"
ZOHO_API_AUTH = "https://accounts.zoho.com/oauth/v2/token"
SUBGRAPH_API = "https://graph.dao.teledisko.com/subgraphs/name/TelediskoDAO/dao"
EMAIL_FROM = "dao@teledisko.com"
EMAIL_TO = "benjamin@teledisko.com"
EMAIL_CC = "alberto@granzotto.net,stefano.ceschib@gmail.com,miotto@posteo.de"
ODOO_API = "https://odoo.teledisko.com/jsonrpc"
DAO_URL = "https://dao.teledisko.com"

[secrets]
# ZOHO_CLIENT_ID
# ZOHO_CLIENT_SECRET
# ZOHO_REFRESH_TOKEN
# ODOO_USERNAME
# ODOO_PASSWORD

[miniflare]
env_path = ".env.test"             # --env
kv_persist = false                  # --kv-persist
cache_persist = "./cache"          # --cache-persist
host = "127.0.0.1"                 # --host
port = 1337                        # --port